NUM_LETTERS = 26

# Colors
WHITE_COLOR = 255
BLACK_COLOR = 0

# Canvas size settings - ONLY EDIT BIG_WIDTH
BIG_WIDTH = 420
COMPRESSED_WIDTH = 28
PIXEL_SIZE = BIG_WIDTH // COMPRESSED_WIDTH

# Key codes for OpenCV
ESC_KEY = 27
SPACE_KEY = 32
Q_KEY = 113
E_KEY = 101